#version: "3.9"

x-volumes: &volumes
  - ${HOME}/exp:/home/ezdev/exp
  - ${HOME}/unity-envs:/home/ezdev/unity-envs
  - ${HOME}/workspaces:/home/ezdev/workspaces
  - /data:/data
  - /tmp/.X11-unix:/tmp/.X11-unix:rw
  - ${XAUTHORITY}:${XAUTHORITY}
  - $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR
  - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d

x-service-runtime: &service-runtime
    environment:
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - XAUTHORITY
      - XDG_RUNTIME_DIR
    volumes: *volumes
    working_dir: /home/ezdev/exp

x-deploy-nvidia: &deploy-nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              #device_ids: ['0', '3']
              capabilities: [gpu]

services:
  navsim-1:
    <<: [*service-runtime, *deploy-nvidia]
    image: ghcr.io/ucf-sttc/navsim/navsim:1.0.0-navsim
    container_name: navsim-1
    command: bash -c "nvidia-smi; vulkaninfo; which python; python -V;
             which conda; conda -V; which mamba; mamba -V; echo 'torch.cuda:';
             python -c 'import torch; print(torch.cuda.is_available())'; while sleep 1000; do :; done"

  navsim-1-build:
    <<: [*service-runtime, *deploy-nvidia]
    image: ghcr.io/ucf-sttc/navsim/navsim:1.0.0-navsim
    container_name: navsim-buuild
    command: bash -c "nvidia-smi; vulkaninfo; which python; python -V;
             which conda; conda -V; which mamba; mamba -V; echo 'torch.cuda:';
             python -c 'import torch; print(torch.cuda.is_available())'"
    build: 
      context: ./tools
      dockerfile: dockerfiles/Dockerfile-navsim
      args:
        - from=debian:11.6-slim

  navsim-1-fixid:
    image: ghcr.io/ucf-sttc/navsim/navsim:1.0.0-navsim
    build: 
      context: ./tools
      dockerfile: dockerfiles/Dockerfile-navsim-fixid
      args:
        - img=ghcr.io/ucf-sttc/navsim/navsim:1.0.0-navsim

  nvidia-test:
    <<: [*deploy-nvidia, *service-runtime]
    image: debian:11.6-slim
    container_name: nvidia-test
    command: bash -c "nvidia-smi"