ARG from
FROM ${from}
LABEL org.opencontainers.image.authors="armando@cortixly.ai"

ENV DEBIAN_FRONTEND=noninteractive
ENV NAVSIM_DIR="/opt/navsim"
#ARG COMPONENTS=Unity,Windows,Windows-Mono,Mac,Mac-Mono,WebGL
#ARG COMPONENTS=Unity,Mac,WebGL

RUN apt-get -q update \
    && apt-get -qq install -y --no-install-recommends \
		  unzip \
    && apt-get -q autoremove --purge && apt-get -q clean && rm -rf /var/lib/apt/lists/*


USER root
WORKDIR /root/
SHELL ["/bin/bash", "-c"]

#COPY scripts/activate-conda-base.sh /opt/container-scripts/entrypoint.d/20-activate-conda-base.sh

#RUN which python && which conda && which mamba
#install phoronix
#RUN wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_10.4.0_all.deb && \
#    gdebi phoronix-test-suite_10.4.0_all.deb && \
#    rm phoronix-test-suite_10.4.0_all.deb
#RUN dpkg -i phoronix-test-suite_10.4.0_all.deb
#COPY test-profiles/local /var/lib/phoronix-test-suite/test-profiles/

#Install MINICONDA and navsim_env in base
#COPY scripts/* ezai-conda* ezai-pip-* repo.zip /root/

#RUN ls -l /root/navsim-repo/navsim-mlagents/
#RUN read -p "Press any key to resume ..."
#COPY mlagents_patch /root/mlagents_patch
#RUN chmod +x /root/*.sh && \
#    source ezai-conda.sh && \
#    install_miniconda --conda_dir ${CONDA_DIR}
#ENV PATH=${CONDA_DIR}/bin:$PATH
#ENV BASH_ENV="/root/.bashrc"
COPY repo.zip /root/
#RUN mkdir -p ${NAVSIM_DIR}
RUN unzip -d ${NAVSIM_DIR} repo.zip && rm repo.zip && chmod -R 777 ${NAVSIM_DIR}
    #source /root/.bashrc && source /root/ezai-conda.sh && \
    #ezai_conda_create --venv "base" && \
    #activate base && \

#TODO: bin/bash doesnt activate base so have to do here
RUN source /opt/py/etc/profile.d/conda.sh && conda activate base && \
    cd $NAVSIM_DIR && ./install-repo.sh

#ENTRYPOINT ["bash", "-c", "(/root/chuser.sh && python /root/x_server.py) && bash"]
#ENTRYPOINT ["/root/entrypoint.sh"]
#CMD ["bash"]