#version: "3.9"

x-volumes: &volumes
  - ${HOME}/exp:/home/ezdev/exp
  - ${HOME}/unity-envs:/home/ezdev/unity-envs
  - ${HOME}/workspaces:/home/ezdev/workspaces
  - /data:/data
  - /tmp/.X11-unix:/tmp/.X11-unix:rw
  - ${XAUTHORITY}:${XAUTHORITY}
  - $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR
  - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d

x-service-runtime: &service-runtime
    environment:
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - XAUTHORITY
      - XDG_RUNTIME_DIR
    volumes: *volumes
    working_dir: /home/ezdev/exp

x-deploy-nvidia: &deploy-nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              #device_ids: ['0', '3']
              capabilities: [gpu]

services:
  navsim-1:
    <<: [*service-runtime, *deploy-nvidia]
    image: ghcr.io/ucf-sttc/navsim/navsim:1.0.0-navsim
    container_name: navsim-test
    command: bash -c "nvidia-smi; vulkaninfo; which python; python -V;
             which conda; conda -V; which mamba; mamba -V; echo 'torch.cuda:';
             python -c 'import torch; print(torch.cuda.is_available())'"
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile-navsim
      args:
        - from=debian:11.6-slim
        - duid=1003
        - dgid=1003

  navsim-1-fixid:
    <<: [*service-runtime]
    image: ghcr.io/ucf-sttc/navsim/navsim:1.0.0-navsim
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile-navsim-fixid
      args:
        - from=ghcr.io/ucf-sttc/navsim/navsim:1.0.0-navsim
        - duid=1003
        - dgid=1003


  nvidia-test1:
    image: ubuntu:20.04
    container_name: nvidia-test
    command: bash -c "nvidia-smi"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY

  nvidia-test2:
    image: ubuntu:20.04
    container_name: nvidia-test2
    command: bash -c "nvidia-smi"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              #device_ids: ['0', '3']
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY

  vulkan-test1:
    #image: nvidia/vulkan:1.2.133-450
    image: nvidia/vulkan:1.2.170-470
    container_name: vulkan-test
    command: bash -c "nvidia-smi; vulkaninfo"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              #device_ids: ['0', '3']
              capabilities: [gpu]
